spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ben?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      enable: true
      filters: stat,wall,log4j2
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    suffix: .html
  redis:
    host: 127.0.0.1
shiro:
  loginUrl: /login
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ben.shiro.pojo.bo
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl