server:
  port: 8803
spring:
  profiles:
    active: dev
    include: shiro
  http:
    encoding:
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    redis:
      namespace: spring:session