spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ben?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
shiro:
  loginUrl: /login
  enabled: true
  successUrl: /dataDict/list
  web:
    enabled: true